name: 'Setup Bun and Install Dependencies'
description: 'Setup Bun and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.1

    - name: Install dependencies
      shell: bash
      working-directory: 5e-quick-monsters
      run: bun ci
